# Generated by Django 3.2.2 on 2021-05-11 22:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                ("roll_number", models.CharField(max_length=15, unique=True)),
                ("name", models.CharField(max_length=300)),
                ("current_year", models.IntegerField(default=1)),
                ("current_sem", models.IntegerField(default=1)),
                ("branch", models.CharField(default="IT", max_length=8)),
                ("section", models.CharField(blank=True, max_length=2)),
                ("current_status", models.CharField(default="Studying", max_length=30)),
                ("std_pass", models.CharField(max_length=10)),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "cgpa",
                    models.CharField(blank=True, default="NA", max_length=5, null=True),
                ),
                (
                    "last_refreshed",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
