# Generated by Django 3.2.5 on 2021-07-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="branch",
            field=models.CharField(default="Others", max_length=100),
        ),
    ]
