# Generated by Django 3.2.2 on 2021-05-11 22:16

from django.db import migrations, models

import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("index", models.CharField(max_length=50)),
                ("published_date", models.DateField()),
                ("content", models.TextField()),
                ("slug", models.SlugField(default=news.models.generate_id, unique=True)),
                ("link", models.URLField(max_length=300)),
                ("categories", models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                "verbose_name_plural": "News",
                "ordering": ["-published_date"],
            },
        ),
    ]
