# Generated by Django 3.2.6 on 2021-08-15 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import syncing.utilities.status_codes


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("semesters", "0005_semesterblock_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(auto_now_add=True)),
                ("task_type", models.CharField(max_length=40)),
                ("persons_synced", models.IntegerField(default=0)),
                ("persons_failed", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        default=syncing.utilities.status_codes.SyncStatusCodes["IN_PROGRESS"],
                        max_length=40,
                    ),
                ),
                ("sync_per_cycle", models.IntegerField(default=16)),
            ],
        ),
        migrations.CreateModel(
            name="Signup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.BooleanField(default=False)),
                (
                    "logs",
                    models.CharField(default="SIGNUP__NOT_YET_STARTED", max_length=40),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FailedSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(default="FAILED__SYNC_CORRUPT", max_length=40),
                ),
                ("logs", models.CharField(max_length=100)),
                (
                    "semester",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="semesters.semester",
                    ),
                ),
            ],
        ),
    ]
