# Generated by Django 3.2.6 on 2021-08-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("syncing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="signup",
            name="attendance_pending",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AddField(
            model_name="signup",
            name="result_pending",
            field=models.CharField(default="", max_length=15),
        ),
    ]
