# Generated by Django 3.2.5 on 2021-07-24 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("semesters", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="semester",
            name="assn1_per",
        ),
        migrations.RemoveField(
            model_name="semester",
            name="assn2_per",
        ),
        migrations.RemoveField(
            model_name="semester",
            name="assn3_per",
        ),
        migrations.RemoveField(
            model_name="semester",
            name="int1_per",
        ),
        migrations.RemoveField(
            model_name="semester",
            name="int2_per",
        ),
        migrations.RemoveField(
            model_name="semester",
            name="quiz1_per",
        ),
        migrations.RemoveField(
            model_name="semester",
            name="quiz2_per",
        ),
        migrations.RemoveField(
            model_name="semester",
            name="quiz3_per",
        ),
    ]
