# Generated by Django 3.2.5 on 2021-07-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("semesters", "0003_auto_20210728_1051"),
    ]

    operations = [
        migrations.AddField(
            model_name="semester",
            name="current_status",
            field=models.CharField(default="Studying", max_length=100),
        ),
    ]
