# Generated by Django 3.2.6 on 2021-08-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("semesters", "0004_semester_current_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="semesterblock",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
