# Generated by Django 3.2.2 on 2021-05-11 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("semesters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20)),
                ("full_name", models.CharField(blank=True, max_length=100, null=True)),
                ("lecturer", models.CharField(blank=True, max_length=150, null=True)),
                ("year", models.CharField(default="NA", max_length=15)),
                ("semester", models.IntegerField()),
                ("branch", models.CharField(default="IT", max_length=5)),
                ("section", models.CharField(blank=True, max_length=2)),
            ],
            options={
                "ordering": ["year", "semester", "branch", "section", "name"],
            },
        ),
        migrations.CreateModel(
            name="SubjectBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("total", models.IntegerField(default=0)),
                ("present", models.IntegerField(default=0)),
                ("absent", models.IntegerField(default=0)),
                ("int1_max", models.FloatField(default=0)),
                ("int1", models.FloatField(default=0)),
                ("int2_max", models.FloatField(default=0)),
                ("int2", models.FloatField(default=0)),
                ("assn1_max", models.FloatField(default=0)),
                ("assn1", models.FloatField(default=0)),
                ("assn2_max", models.FloatField(default=0)),
                ("assn2", models.FloatField(default=0)),
                ("assn3_max", models.FloatField(default=0)),
                ("assn3", models.FloatField(default=0)),
                ("quiz1_max", models.FloatField(default=0)),
                ("quiz1", models.FloatField(default=0)),
                ("quiz2_max", models.FloatField(default=0)),
                ("quiz2", models.FloatField(default=0)),
                ("quiz3_max", models.FloatField(default=0)),
                ("quiz3", models.FloatField(default=0)),
                ("sess_max", models.FloatField(default=0)),
                ("sess", models.FloatField(default=0)),
                ("ext_grade", models.CharField(default="NA", max_length=3)),
                ("ext_sub_credits", models.IntegerField(default=0)),
                ("ext_grade_pts", models.IntegerField(default=0)),
                ("semester", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="semesters.semester")),
                ("subject", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="subjects.subject")),
            ],
            options={
                "ordering": ["-semester__semester", "-semester__student__name", "subject__name"],
            },
        ),
    ]
