# Generated by Django 3.2.2 on 2021-05-11 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subjects", "__first__"),
        ("semesters", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("present", models.IntegerField(default=0)),
                ("absent", models.IntegerField(default=0)),
                ("total", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["attendance_block__semester__student", "-date"],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("did_attend", models.BooleanField(null=True)),
                ("start", models.CharField(blank=True, max_length=20, null=True)),
                ("end", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "attendance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sessions", to="attendance.attendance"
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="subject", to="subjects.subject"
                    ),
                ),
            ],
            options={
                "ordering": ["attendance__attendance_block__semester__student", "-attendance__date", "start"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("link", models.URLField(default="http://vceresults.in/", max_length=300)),
                ("total", models.IntegerField(default=0)),
                ("present", models.IntegerField(default=0)),
                ("absent", models.IntegerField(default=0)),
                ("percent", models.FloatField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "semester",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="semesters.semester"),
                ),
            ],
            options={
                "ordering": ["semester__student", "-semester__semester"],
            },
        ),
        migrations.AddField(
            model_name="attendance",
            name="attendance_block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="attendance", to="attendance.attendanceblock"
            ),
        ),
    ]
